// File generated by FlutterFire CLI / Custom configuration template
// Ignore lint rules for auto-generated constants
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzJySIMXnwFVatk5wLluz7P-JdDjIbpLM',
    appId: '1:15355084605:web:41c95a1d1253cb4b640f54',
    messagingSenderId: '15355084605',
    projectId: 'nsrit-canteen-4de4b',
    authDomain: 'nsrit-canteen-4de4b.firebaseapp.com',
    storageBucket: 'nsrit-canteen-4de4b.firebasestorage.app',
    measurementId: 'G-CV99VCC7HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUhLwIVb3wgA6rWsCBIIDKnXhfIaLcF54',
    appId: '1:15355084605:android:10b75113bed73f5b640f54',
    messagingSenderId: '15355084605',
    projectId: 'nsrit-canteen-4de4b',
    storageBucket: 'nsrit-canteen-4de4b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXhcq3tOKkFMo6fTDNBZTQkrgRrmqyxwU',
    appId: '1:15355084605:ios:dcbe6e064190aeea640f54',
    messagingSenderId: '15355084605',
    projectId: 'nsrit-canteen-4de4b',
    storageBucket: 'nsrit-canteen-4de4b.firebasestorage.app',
    iosBundleId: 'com.example.nsritCanteen',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXhcq3tOKkFMo6fTDNBZTQkrgRrmqyxwU',
    appId: '1:15355084605:ios:dcbe6e064190aeea640f54',
    messagingSenderId: '15355084605',
    projectId: 'nsrit-canteen-4de4b',
    storageBucket: 'nsrit-canteen-4de4b.firebasestorage.app',
    iosBundleId: 'com.example.nsritCanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzJySIMXnwFVatk5wLluz7P-JdDjIbpLM',
    appId: '1:15355084605:web:955fc8358bba4941640f54',
    messagingSenderId: '15355084605',
    projectId: 'nsrit-canteen-4de4b',
    authDomain: 'nsrit-canteen-4de4b.firebaseapp.com',
    storageBucket: 'nsrit-canteen-4de4b.firebasestorage.app',
    measurementId: 'G-B3FKH94FZ7',
  );
}
